# Generated by Django 4.1 on 2022-09-29 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_alter_todotask_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='todotask',
            name='task_isfinished',
            field=models.BooleanField(default=False),
        ),
    ]
