# Generated by Django 4.1 on 2022-10-05 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0004_alter_todotask_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='task_isfinished',
            field=models.CharField(default='Not Finished', max_length=5),
        ),
    ]
