# Generated by Django 4.1 on 2022-10-05 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0005_alter_todotask_task_isfinished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todotask',
            name='task_isfinished',
            field=models.BooleanField(default=False),
        ),
    ]
