# Generated by Django 4.1 on 2022-09-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_watched', models.TextField()),
                ('item_title', models.TextField()),
                ('item_rating', models.IntegerField()),
                ('item_release_date', models.CharField(max_length=255)),
                ('item_review', models.TextField()),
            ],
        ),
    ]
